-- MySQL Script generated by MySQL Workbench
-- Sun Aug 14 21:45:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaDeRecomendacionDeInversiones
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SistemaDeRecomendacionDeInversiones` ;

-- -----------------------------------------------------
-- Schema SistemaDeRecomendacionDeInversiones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaDeRecomendacionDeInversiones` DEFAULT CHARACTER SET utf8 ;
USE `SistemaDeRecomendacionDeInversiones` ;

-- -----------------------------------------------------
-- Table `SistemaDeRecomendacionDeInversiones`.`Inversionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeRecomendacionDeInversiones`.`Inversionista` (
  `id_Inversionista` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `Criptomonedas` VARCHAR(45) NOT NULL,
  `Interes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Inversionista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeRecomendacionDeInversiones`.`Criptomoneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeRecomendacionDeInversiones`.`Criptomoneda` (
  `id_Criptomoneda` INT NOT NULL,
  `Inversionista_id_Inversionista` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Disponibilidad` FLOAT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Historico` DATE NOT NULL,
  PRIMARY KEY (`id_Criptomoneda`, `Inversionista_id_Inversionista`),
  CONSTRAINT `fk_Criptomoneda_Inversionista`
    FOREIGN KEY (`Inversionista_id_Inversionista`)
    REFERENCES `SistemaDeRecomendacionDeInversiones`.`Inversionista` (`id_Inversionista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Criptomoneda_Inversionista_idx` ON `SistemaDeRecomendacionDeInversiones`.`Criptomoneda` (`Inversionista_id_Inversionista` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SistemaDeRecomendacionDeInversiones`.`Precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeRecomendacionDeInversiones`.`Precio` (
  `id_Precio` INT NOT NULL,
  `Criptomoneda_id_Criptomoneda` INT NOT NULL,
  `ValorActual` INT NOT NULL,
  `Capitalizacion` FLOAT NOT NULL,
  `Volumen` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`id_Precio`, `Criptomoneda_id_Criptomoneda`),
  CONSTRAINT `fk_Precio_Criptomoneda1`
    FOREIGN KEY (`Criptomoneda_id_Criptomoneda`)
    REFERENCES `SistemaDeRecomendacionDeInversiones`.`Criptomoneda` (`id_Criptomoneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Precio_Criptomoneda1_idx` ON `SistemaDeRecomendacionDeInversiones`.`Precio` (`Criptomoneda_id_Criptomoneda` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
