-- MySQL Script generated by MySQL Workbench
-- Mon Aug 15 19:17:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaDeRecomendacionDeInversiones
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SistemaDeRecomendacionDeInversiones` ;

-- -----------------------------------------------------
-- Schema SistemaDeRecomendacionDeInversiones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaDeRecomendacionDeInversiones` DEFAULT CHARACTER SET utf8 ;
USE `SistemaDeRecomendacionDeInversiones` ;

-- -----------------------------------------------------
-- Table `SistemaDeRecomendacionDeInversiones`.`Inversionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeRecomendacionDeInversiones`.`Inversionista` (
  `id_Inversionista` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `Criptomonedas` VARCHAR(45) NOT NULL,
  `Interes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Inversionista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeRecomendacionDeInversiones`.`Valor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeRecomendacionDeInversiones`.`Valor` (
  `id_Valor` INT NOT NULL,
  `ValorActual` INT NOT NULL,
  `Capitalizacion` FLOAT NOT NULL,
  `Volumen` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`id_Valor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeRecomendacionDeInversiones`.`Criptomoneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeRecomendacionDeInversiones`.`Criptomoneda` (
  `id_Criptomoneda` INT NOT NULL,
  `id_Inversionista` INT NOT NULL,
  `id_Valor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Disponibilidad` FLOAT NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Historico` DATE NOT NULL,
  PRIMARY KEY (`id_Criptomoneda`, `id_Inversionista`, `id_Valor`),
  CONSTRAINT `fk_Criptomoneda_Inversionista`
    FOREIGN KEY (`id_Inversionista`)
    REFERENCES `SistemaDeRecomendacionDeInversiones`.`Inversionista` (`id_Inversionista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Criptomoneda_Valor1`
    FOREIGN KEY (`id_Valor`)
    REFERENCES `SistemaDeRecomendacionDeInversiones`.`Valor` (`id_Valor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_Criptomoneda_Inversionista_idx` ON `SistemaDeRecomendacionDeInversiones`.`Criptomoneda` (`id_Inversionista` ASC) VISIBLE;

CREATE INDEX `fk_Criptomoneda_Valor1_idx` ON `SistemaDeRecomendacionDeInversiones`.`Criptomoneda` (`id_Valor` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
